backend:
  name: git-gateway  # you can keep git-gateway if you plan to commit to GitHub
  branch: main       # your branch

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "excerpt", label: "Excerpt", widget: "text" }
      - { name: "body", label: "Body", widget: "markdown" }
